/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import control.Tarea;
import vista.AgregarTarea;
/**
 *
 * @author eduardo
 */
public class App extends javax.swing.JFrame {
    
    /**
     * Creates new form App
     */
    public App() {
        initComponents(); 
        tarea=new Tarea();
        tarea.consultarFechasRegistradas(cbbFechasFiltro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dsktpPnlMain = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cbbFechasFiltro = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mIAgregar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TITULO", "DESCRIPCION", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        cbbFechasFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODAS LAS TAREAS" }));
        cbbFechasFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbFechasFiltroActionPerformed(evt);
            }
        });

        dsktpPnlMain.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dsktpPnlMain.setLayer(cbbFechasFiltro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dsktpPnlMainLayout = new javax.swing.GroupLayout(dsktpPnlMain);
        dsktpPnlMain.setLayout(dsktpPnlMainLayout);
        dsktpPnlMainLayout.setHorizontalGroup(
            dsktpPnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dsktpPnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dsktpPnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addComponent(cbbFechasFiltro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        dsktpPnlMainLayout.setVerticalGroup(
            dsktpPnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dsktpPnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbbFechasFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("File");

        mIAgregar.setText("Agregar");
        mIAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mIAgregarActionPerformed(evt);
            }
        });
        jMenu1.add(mIAgregar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dsktpPnlMain)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dsktpPnlMain)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mIAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mIAgregarActionPerformed
        AgregarTarea at =  new AgregarTarea();
        dsktpPnlMain.add(at);
        at.toFront();
        at.setVisible(true);
    }//GEN-LAST:event_mIAgregarActionPerformed

    private void cbbFechasFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbFechasFiltroActionPerformed
        
    }//GEN-LAST:event_cbbFechasFiltroActionPerformed
    private Tarea tarea;
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbbFechasFiltro;
    private javax.swing.JDesktopPane dsktpPnlMain;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem mIAgregar;
    // End of variables declaration//GEN-END:variables
}
